# SPDX-FileCopyrightText: Copyright (c) 2023 - 2026 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff-check
        args: [--fix]
        exclude: ^examples/
      - id: ruff-format

-   repo: local
    hooks:
    - id: interrogate
      name: interrogate
      entry: python test/ci_tests/check_docstring_coverage.py
      language: python
      types: [python]
      additional_dependencies: ['interrogate==1.7.0']
      exclude: ^docs/|^physicsnemo/experimental/|^test/

-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
    - id: markdownlint
      exclude: ^skills/

-   repo: local
    hooks:
    - id: license
      name: license
      entry: python test/ci_tests/header_check.py
      language: python
      additional_dependencies: ['GitPython']
      files: \.(py|yaml|ci|release)$|Dockerfile$
      exclude: ^(physicsnemo/internal/|docs/)

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: check-added-large-files
      args: [--maxkb=5000]

-   repo: https://github.com/seddonym/import-linter
    rev: v2.5.2
    hooks:
    - id: import-linter
      args: [--verbose]